[Domain]
Name=Kubuntu
Name[bs]=Kubuntu
Name[ca]=Kubuntu
Name[ca@valencia]=Kubuntu
Name[da]=Kubuntu
Name[de]=Kubuntu
Name[el]=Kubuntu
Name[en_GB]=Kubuntu
Name[es]=Kubuntu
Name[et]=Kubuntu
Name[fi]=Kubuntu
Name[fr]=Kubuntu
Name[gl]=Kubuntu
Name[hu]=Kubuntu
Name[it]=Kubuntu
Name[kk]=Kubuntu
Name[ko]=쿠분투
Name[lt]=Kubuntu
Name[mr]=कुबुन्टु
Name[nb]=Kubuntu
Name[nds]=Kubuntu
Name[nl]=Kubuntu
Name[pl]=Kubuntu
Name[pt]=Kubuntu
Name[pt_BR]=Kubuntu
Name[ro]=Kubuntu
Name[ru]=Kubuntu
Name[sk]=Kubuntu
Name[sl]=Kubuntu
Name[sr]=Кубунту
Name[sr@ijekavian]=Кубунту
Name[sr@ijekavianlatin]=Kubuntu
Name[sr@latin]=Kubuntu
Name[sv]=Kubuntu
Name[tr]=Kubuntu
Name[ug]=كۇبۇنتۇ
Name[uk]=Kubuntu
Name[x-test]=xxKubuntuxx
Name[zh_CN]=Kubuntu
Name[zh_TW]=Kubuntu
Icon=package-x-generic
URL=http://www.kubuntu.org

[@QAPT_WORKER_RDN_VERSIONED@.updatecache]
Name=Update package information
Name[bs]=Ažuriraj paketske informacije
Name[ca]=Actualització de la informació dels paquets
Name[ca@valencia]=Actualització de la informació dels paquets
Name[da]=Information om opdateringspakke
Name[de]=Paketinformation aktualisieren
Name[el]=Ενημέρωση πληροφοριών πακέτων
Name[en_GB]=Update package information
Name[es]=Actualizar información de paquetes
Name[et]=Paketi teabe uuendamine
Name[fi]=Pakettitietojen päivittäminen
Name[fr]=Mettre à jour les informations de mise à jour
Name[gl]=Actualizar a información do paquete
Name[hu]=Csomaginformációk frissítése
Name[it]=Aggiorna le informazioni del pacchetto
Name[kk]=Десте мәліметін жаңарту
Name[ko]=패키지 정보 업데이트
Name[lt]=Atnaujinti paketų informaciją
Name[mr]=पॅकेज माहिती अद्ययावत करा
Name[nb]=Oppdater informasjon om pakker
Name[nds]=Paketinformatschonen opfrischen
Name[nl]=Pakketinformatie bijwerken
Name[pl]=Informacje o pakiecie uaktualniającym
Name[pt]=Actualizar a informação dos pacotes
Name[pt_BR]=Atualizar as informações do pacote
Name[ro]=Actualizează informațiile despre pachete
Name[ru]=Обновление сведений о пакете
Name[sk]=Aktualizovať informácie o balíkoch
Name[sl]=Posodobi podrobnosti o paketih
Name[sr]=Ажурирај податке о пакетима
Name[sr@ijekavian]=Ажурирај податке о пакетима
Name[sr@ijekavianlatin]=Ažuriraj podatke o paketima
Name[sr@latin]=Ažuriraj podatke o paketima
Name[sv]=Uppdatera paketinformation
Name[tr]=Paket bilgisini güncelle
Name[ug]=بوغچىغا مۇناسىۋەتلىك ئۇچۇرلارنى يېڭىلاش
Name[uk]=Оновлення даних щодо пакунків
Name[x-test]=xxUpdate package informationxx
Name[zh_CN]=更新软件包信息
Name[zh_TW]=更新套件資訊
Description=To update the software catalog you need to authenticate.
Description[bs]=Za ažuriranje softverskog kataloga potrebna je autentifikacija
Description[ca]=Heu d'autenticar-vos per actualitzar el catàleg de programari.
Description[ca@valencia]=Heu d'autenticar-vos per actualitzar el catàleg de programari.
Description[da]=Du skal autentificere for at kunne opdatere softwarekataloget.
Description[de]=Zur Aktualisierung Ihres Software-Katalogs müssen Sie sich authentifizieren.
Description[el]=Για την ενημέρωση του καταλόγου λογισμικού χρειάζεστε ταυτοποίηση.
Description[en_GB]=To update the software catalogue you need to authenticate.
Description[es]=Necesita autenticarse para actualizar el catálogo de software.
Description[et]=Tarkvara uuendamiseks tuleb autentida.
Description[fi]=Tunnistaudu päivittääksesi ohjelmaluettelon.
Description[fr]=Pour mettre à jour le catalogue des logiciels, vous devez vous authentifier.
Description[gl]=Para actualizar o catálogo de software precisas autenticarte.
Description[hu]=A szoftverkatalógus frissítéséhez hitelesítés szükséges.
Description[it]=Per aggiornare il catalogo dei programmi devi autenticarti.
Description[kk]=Бағдарламалар каталогын жаңарту үшін аутентификациядан өту қажет.
Description[ko]=소프트웨어 카탈로그를 업데이트하려면 인증해야 합니다.
Description[lt]=Kad atnaujinti programinės įrangos katalogą turite patvirtinti tapatybę.
Description[mr]=सॉफ़्टवेअर सूची अद्ययावत करण्याकरीता तुमची परवानगी घेण्याची गरज आहे.
Description[nb]=Du må autentisere deg for å oppdatere programvarekatalogen.
Description[nds]=Du muttst Dien Identiteet wiesen, ehr Du den Software-Kataloog opfrischen dörvst.
Description[nl]=Om de catalogus met software bij te werken moet u zich authenticeren.
Description[pl]=Aby uaktualnić katalog oprogramowania musisz uwierzytelnić.
Description[pt]=Para actualizar o catálogo de aplicações, tem de se autenticar.
Description[pt_BR]=Para atualizar o catálogo de programas você precisa se autenticar.
Description[ro]=Trebuie să vă autentificați pentru a actualiza catalogul de aplicații.
Description[ru]=Для обновления каталога программ требуется аутентификация.
Description[sk]=Na aktualizáciu katalógu softvéru sa musíte overiť.
Description[sl]=Da posodobite katalog programske opreme, se morate overiti.
Description[sr]=За ажурирање каталога софтвера морате се аутентификовати.
Description[sr@ijekavian]=За ажурирање каталога софтвера морате се аутентификовати.
Description[sr@ijekavianlatin]=Za ažuriranje kataloga softvera morate se autentifikovati.
Description[sr@latin]=Za ažuriranje kataloga softvera morate se autentifikovati.
Description[sv]=För att uppdatera programvarukatalogen måste du utföra behörighetskontroll.
Description[tr]=Yazılım kataloğunu güncellemek için kimlik doğrulamanız gerekiyor.
Description[ug]=يۇمشاق دېتال كاتالوگىنى يېڭىلاش ئۈچۈن دەلىللەش زۆرۈردۇر
Description[uk]=Для оновлення каталогу програмного забезпечення вам слід пройти розпізнавання.
Description[x-test]=xxTo update the software catalog you need to authenticate.xx
Description[zh_CN]=更新软件分类需要您进行认证。
Description[zh_TW]=要更新軟體類別，您必須通過認證。
Policy=yes
Persistence=session

[@QAPT_WORKER_RDN_VERSIONED@.commitchanges]
Name=Install or remove packages
Name[bs]=Instalacija i pregled softverskih paketa
Name[ca]=Instal·la i suprimeix paquets de programari
Name[ca@valencia]=Instal·la i suprimeix paquets de programari
Name[cs]=Instalovat nebo odstranit balíčky
Name[da]=Installér eller fjern pakker
Name[de]=Pakete installieren oder entfernen
Name[el]=Εγκατάσταση ή αφαίρεση πακέτων
Name[en_GB]=Install or remove packages
Name[es]=Instalar o eliminar paquetes
Name[et]=Tarkvarapakettide paigaldamine ja eemaldamine
Name[fi]=Pakettien asentaminen ja poistaminen
Name[fr]=Installer ou supprimer des paquets
Name[gl]=Instalar ou eliminar paquetes
Name[hu]=Csomagok telepítése és eltávolítása
Name[it]=Installa o rimuovi i pacchetti
Name[kk]=Дестелерді орнату мен өшіру
Name[ko]=패키지 설치 및 삭제
Name[lt]=Įdiegti ir pašalinti paketus
Name[mr]=पॅकेजेस प्रतिष्ठापीत करा किंवा काढून टाका
Name[nb]=Installer eller fjern pakker
Name[nds]=Paketen installeren oder wegmaken
Name[nl]=Installeer en verwijder pakketten
Name[pl]=Instaluj lub usuwaj pakiety
Name[pt]=Instalar ou remover pacotes
Name[pt_BR]=Instalar ou remover pacotes
Name[ro]=Instalează sau elimină pachete
Name[ru]=Установка и удаление пакетов
Name[sk]=Inštalovať a odstrániť balíky
Name[sl]=Namesti ali odstrani pakete
Name[sr]=Инсталирај или уклони пакете
Name[sr@ijekavian]=Инсталирај или уклони пакете
Name[sr@ijekavianlatin]=Instaliraj ili ukloni pakete
Name[sr@latin]=Instaliraj ili ukloni pakete
Name[sv]=Installera eller ta bort paket
Name[tr]=Yazılım paketlerini kur veya kaldır
Name[ug]=بوغچىلارنى ئورنىتىش ياكى ئۆچۈرۈش
Name[uk]=Встановлення або вилучення пакунків
Name[x-test]=xxInstall or remove packagesxx
Name[zh_CN]=安装或移除软件包
Name[zh_TW]=安裝或移除套件
Description=To install or remove software you need to authenticate.
Description[bs]=Za instalaciju ili uklanjanje softvera treba se autentificirati
Description[ca]=Heu d'autenticar-vos per instal·lar o suprimir programari.
Description[ca@valencia]=Heu d'autenticar-vos per instal·lar o suprimir programari.
Description[da]=Du skal autentificere for at kunne installere eller fjerne software.
Description[de]=Zum Installieren oder Entfernen von Software müssen Sie sich authentifizieren.
Description[el]=Για να εγκαταστήσετε ή να αφαιρέσετε λογισμικό χρειάζεστε ταυτοποίηση.
Description[en_GB]=To install or remove software you need to authenticate.
Description[es]=Necesita autenticarse para instalar o eliminar software.
Description[et]=Tarkvara paigaldamiseks või eemaldamiseks tuleb autentida.
Description[fi]=Tunnistaudu asentaaksesi tai poistaaksesi ohjelmia.
Description[fr]=Pour installer ou supprimer des logiciels, vous devez vous authentifier.
Description[gl]=Para instalar ou desinstalar software precisa autenticarse.
Description[hu]=Csomagok telepítéséhez vagy eltávolításához hitelesítés szükséges.
Description[it]=Per installare o rimuovere i programmi devi autenticarti.
Description[kk]=Бағдарламаларды орнату мен өшіру үшін аутентификациядан өту қажет.
Description[ko]=패키지를 설치 및 삭제하려면 인증해야 합니다.
Description[lt]=Kad įdiegti ar pašalinti programinę įrangą turite patvirtinti tapatybę.
Description[mr]=सॉफ़्टवेअर प्रतिष्ठापीत करण्याकरीता किंवा काढण्याकरिता तुमची परवानगी घेण्याची गरज आहे.
Description[nb]=Du må autentisere deg for å installere eller fjerne programvare.
Description[nds]=Du muttst Dien Identiteet wiesen, ehr Du Software installeren oder wegmaken dörvst.
Description[nl]=Om software te installeren of te verwijderen moet u zich authenticeren.
Description[pl]=Aby zainstalować lub usunąć oprogramowanie musisz uwierzytelnić.
Description[pt]=Para instalar ou remover aplicações, tem de se autenticar.
Description[pt_BR]=Para instalar ou remover programas você precisa se autenticar.
Description[ro]=Trebuie să vă autentificați pentru a instala sau elimina aplicații.
Description[ru]=Для установки и удаления программ требуется аутентификация.
Description[sk]=Na inštaláciu alebo odstránenie softvéru sa musíte overiť.
Description[sl]=Da namestite ali odstranite programsko opremo, se morate overiti.
Description[sr]=За инсталирање или уклањање софтвера морате се аутентификовати.
Description[sr@ijekavian]=За инсталирање или уклањање софтвера морате се аутентификовати.
Description[sr@ijekavianlatin]=Za instaliranje ili uklanjanje softvera morate se autentifikovati.
Description[sr@latin]=Za instaliranje ili uklanjanje softvera morate se autentifikovati.
Description[sv]=För att installera eller ta bort programvara måste du utföra behörighetskontroll.
Description[tr]=Yazılım yüklemek veya kaldırmak için kimlik doğrulamanız gerekiyor.
Description[ug]=يۇمشاق دېتال ئورنىتىش ياكى ئۆچۈرۈش ئۈچۈن دەلىللەش زۆرۈردۇر.
Description[uk]=Для встановлення або вилучення програмного забезпечення вам слід пройти розпізнавання.
Description[x-test]=xxTo install or remove software you need to authenticate.xx
Description[zh_CN]=安装软件需要您进行认证。
Description[zh_TW]=要安裝或移除軟體，您必須通過認證。
Policy=auth_admin
Persistence=session

[@QAPT_WORKER_RDN_VERSIONED@.writefiletodisk]
Name=Change software configuration
Name[bs]=Promjena softverske konfiguracije
Name[ca]=Canvi de la configuració del programari
Name[ca@valencia]=Canvi de la configuració del programari
Name[da]=Skift softwarekonfiguration
Name[de]=Software-Einstellungen ändern
Name[el]=Αλλαγή διαμόρφωσης λογισμικού
Name[en_GB]=Change software configuration
Name[es]=Cambiar la configuración de software
Name[et]=Tarkvaraseadistuse muutmine
Name[fi]=Ohjelmistoasetuksien muuttaminen
Name[fr]=Modifier la configuration des logiciels
Name[gl]=Cambiar a configuración do software
Name[hu]=Szoftverbeállítás módosítása
Name[it]=Cambia la configurazione dei programmi
Name[kk]=Бағдарламаның баптауын өзгерту
Name[ko]=소프트웨어 설정 변경
Name[lt]=Keisti programinės įrangos konfigūraciją
Name[mr]=सॉफ़्टवेअर संयोजना बदला
Name[nb]=Endre programvareoppsett
Name[nds]=Software-Instellen ännern
Name[nl]=Softwareconfiguratie wijzigen
Name[pl]=Zmień konfigurację oprogramowania
Name[pt]=Mudar a configuração das aplicações
Name[pt_BR]=Alterar as configurações do programa
Name[ro]=Modifică configurarea aplicațiilor
Name[ru]=Изменение конфигурации программного обеспечения
Name[sk]=Zmeniť konfiguráciu softvéru
Name[sl]=Spremeni nastavitve programske opreme
Name[sr]=Измени поставу софтвера
Name[sr@ijekavian]=Измени поставу софтвера
Name[sr@ijekavianlatin]=Izmeni postavu softvera
Name[sr@latin]=Izmeni postavu softvera
Name[sv]=Ändra programvaruinställning
Name[tr]=Yazılım yapılandırmasını değiştir
Name[ug]=يۇمشاق دېتال سەپلىمىسىنى ئۆزگەرت
Name[uk]=Зміна налаштувань програмного забезпечення
Name[x-test]=xxChange software configurationxx
Name[zh_CN]=更改软件设置
Name[zh_TW]=變更軟體設定
Description=To change software settings you need to authenticate.
Description[bs]=Za promjenu postavku softvera treba se autentificirati
Description[ca]=Heu d'autenticar-vos per canviar l'arranjament del programari.
Description[ca@valencia]=Heu d'autenticar-vos per canviar l'arranjament del programari.
Description[da]=Du skal autentificere for at kunne skifte softwareindstillinger.
Description[de]=Um Software-Einstellungen zu ändern, müssen Sie sich authentifizieren.
Description[el]=Για να αλλάξετε τις ρυθμίσεις λογισμικού χρειάζεστε ταυτοποίηση.
Description[en_GB]=To change software settings you need to authenticate.
Description[es]=Necesita autenticarse para cambiar las preferencias de software.
Description[et]=Tarkvaraseadistuse muutmiseks tuleb autentida.
Description[fi]=Tunnistaudu muuttaaksesi ohjelmistoasetuksia.
Description[fr]=Pour modifier la configuration des logiciels, vous devez vous authentifier.
Description[gl]=Para cambiar as configuracións de software precisa autenticarse.
Description[hu]=A szoftverbeállítások módosításához hitelesítés szükséges.
Description[it]=Per cambiare le impostazioni dei programmi devi autenticarti.
Description[kk]=Бағдарламаның баптауын өзгерту үшін аутентификациядан өту қажет.
Description[ko]=소프트웨어 설정을 변경하려면 인증해야 합니다.
Description[lt]=Kad pakeisti programinės įrangos nustatymus turite patvirtinti tapatybę.
Description[mr]=सॉफ़्टवेअर संयोजना बदलण्याकरिता तुमची परवानगी घेण्याची गरज आहे.
Description[nb]=Du må autentisere deg for å endre programvareoppsettet.
Description[nds]=Du muttst Dien Identiteet wiesen, ehr Du de Software-Instellen ännern dörvst.
Description[nl]=Om instellingen voor software te wijzigen moet u zich authenticeren.
Description[pl]=Aby zmienić ustawienia oprogramowania musisz uwierzytelnić.
Description[pt]=Para modificar a configuração das aplicações, tem de se autenticar.
Description[pt_BR]=Para alterar as configurações do programa você precisa se autenticar.
Description[ro]=Trebuie să vă autentificați pentru a schimba configurarea aplicațiilor.
Description[ru]=Для изменения конфигурации программного обеспечения требуется аутентификация.
Description[sk]=Na zmenu konfigurácie softvéru sa musíte overiť.
Description[sl]=Da spremenite nastavitve programske opreme, se morate overiti.
Description[sr]=За измену поставки софтвера морате се аутентификовати.
Description[sr@ijekavian]=За измену поставки софтвера морате се аутентификовати.
Description[sr@ijekavianlatin]=Za izmenu postavki softvera morate se autentifikovati.
Description[sr@latin]=Za izmenu postavki softvera morate se autentifikovati.
Description[sv]=För att ändra programvaruinställningar måste du utföra behörighetskontroll.
Description[tr]=Yazılım ayarlarını değiştirmek için kimlik doğrulamanız gerekiyor.
Description[ug]=يۇمشاق دېتال سەپلىمىسىنى ئۆزگەرتىش ئۈچۈن، سالاھىيىتىڭىزنى تەكشۈرۈش زۆرۈر.
Description[uk]=Для внесення змін до параметрів програмного забезпечення вам слід пройти розпізнавання.
Description[x-test]=xxTo change software settings you need to authenticate.xx
Description[zh_CN]=更改软件设置需要您进行认证
Description[zh_TW]=要變更軟體設定，您必須通過認證。
Policy=auth_admin
Persistence=session

[@QAPT_WORKER_RDN_VERSIONED@.cancelforeign]
Name=Cancel the task of another user
Name[bs]=Otkaži zadatak drugog korisnika
Name[ca]=Cancel·la la tasca d'un altre usuari
Name[ca@valencia]=Cancel·la la tasca d'un altre usuari
Name[da]=Annullér en anden brugers opgave
Name[de]=Laufendes Programm eines anderen Benutzers abbrechen
Name[el]=Ακύρωση της εργασίας άλλου χρήστη
Name[en_GB]=Cancel the task of another user
Name[es]=Cancelar la tarea de otro usuario
Name[et]=Teise kasutaja toimingu katkestamine
Name[fi]=Toisen käyttäjän tehtävän peruminen
Name[fr]=Annuler la tâche d'un autre utilisateur
Name[gl]=Cancelar a tarefa doutro usuario
Name[hu]=Egy másik felhasználó feladatának megszakítása
Name[it]=Annulla l'attività di un altro utente
Name[kk]=Басқа пайдаланушының тапсырмасынан қайту
Name[ko]=다른 사용자의 작업 취소
Name[lt]=Nutraukti kito naudotojo užduotį
Name[mr]=दुसऱ्या वापरकर्त्याचे कार्य रद्द करा
Name[nb]=Avbryt en annen brukers oppgave
Name[nds]=En anner Bruker sien Opgaav afbreken
Name[nl]=De taak van een andere gebruiker annuleren
Name[pl]=Anuluj zadanie innego użytkownika
Name[pt]=Cancelar a tarefa de outro utilizador
Name[pt_BR]=Cancelar a tarefa de outro usuário
Name[ro]=Anulează sarcina altui utilizator
Name[ru]=Отменить изменения другого пользователя
Name[sk]=Zrušiť úlohu iného používateľa
Name[sl]=Prekliči opravilo drugega uporabnika
Name[sr]=Откажи задатак другог корисника
Name[sr@ijekavian]=Откажи задатак другог корисника
Name[sr@ijekavianlatin]=Otkaži zadatak drugog korisnika
Name[sr@latin]=Otkaži zadatak drugog korisnika
Name[sv]=Avbryt en annan användares aktivitet.
Name[tr]=Diğer kullanıcının görevlerini iptal et
Name[ug]=باشقا ئىشلەتكۈچىنىڭ ۋەزىپىسىنى(ئىجرا قىلىۋاتقان پروگراممىسىنى) ئەمەلدىن قالدۇرۇش
Name[uk]=Скасування дій, визначених іншим користувачем
Name[x-test]=xxCancel the task of another userxx
Name[zh_CN]=取消另一用户的任务
Name[zh_TW]=取消其他使用者的工作
Description=To cancel someone else's software changes you need to authenticate.
Description[bs]=Za otkazivanje tuđih promjena softvera treba se autentificirati
Description[ca]=Heu d'autenticar-vos per cancel·lar els canvis de programari d'altres.
Description[ca@valencia]=Heu d'autenticar-vos per cancel·lar els canvis de programari d'altres.
Description[da]=Du skal autentificere for at kunne annullere andres softwareændringer.
Description[de]=Um die Software eines anderen Benutzers abzubrechen, müssen Sie sich authentifizieren.
Description[el]=Για να ακυρώσετε τις αλλαγές κάποιου άλλου στο λογισμικό χρειάζεστε ταυτοποίηση.
Description[en_GB]=To cancel someone else's software changes you need to authenticate.
Description[es]=Necesita autenticarse para cancelar los cambios de software de otro usuario.
Description[et]=Kellegi teise tarkvaramuutuste katkestamiseks tuleb autentida.
Description[fi]=Tunnistaudu peruaksesi jonkun toisen ohjelmistomuutokset.
Description[fr]=Pour annuler les changements de logiciels d'un autre utilisateur, vous devez vous authentifier.
Description[gl]=Para cancelar os cambios de software doutros usuarios precisa autenticarse.
Description[hu]=Másik felhasználó szoftverváltozásainak megszakításához hitelesítés szükséges.
Description[it]=Per annullare le modifiche di un altro utente, devi autenticarti.
Description[kk]=Басқалардың бағдарламаларға ендірген өзгерістерден қайту үшін аутентификациядан өту қажет.
Description[ko]=다른 사용자의 소프트웨어 변경을 취소하려면 인증해야 합니다.
Description[lt]=Kad atšaukti kitų padarytus programinės įrangos pakeitimus turite patvirtinti tapatybę.
Description[mr]=दुसऱ्या वापरकर्त्याचे कार्य रद्द करण्याकरीता किंवा काढण्याकरिता तुमची परवानगी घेण्याची गरज आहे.
Description[nb]=Du må autentisere deg for å abryte en annen brukers programvareendringer.
Description[nds]=Du muttst Dien Identiteet wiesen, ehr Du en anner Bruker sien Software-Ännern afbreken dörvst.
Description[nl]=Om wijzigingen in software van iemand anders te wijzigen moet u zich authenticeren.
Description[pl]=Aby anulować zmiany w oprogramowaniu kogoś innego musisz uwierzytelnić.
Description[pt]=Para cancelar as modificações de outra pessoa, terá de se autenticar.
Description[pt_BR]=Para cancelar as alterações feitas por outra pessoa você precisa se autenticar.
Description[ro]=Trebuie să vă autentificați pentru a anula modificările făcute de altcineva în aplicații.
Description[ru]=Для отмены изменений в программное обеспечение, внесённых другим пользователем, требуется аутентификация.
Description[sk]=Na zrušenie softvérových zmien niekoho iného sa musíte overiť.
Description[sl]=Da prekličete spremembe programske opreme nekoga drugega, se morate overiti.
Description[sr]=За отказивање туђих измена у софтверу морате се аутентификовати.
Description[sr@ijekavian]=За отказивање туђих измена у софтверу морате се аутентификовати.
Description[sr@ijekavianlatin]=Za otkazivanje tuđih izmena u softveru morate se autentifikovati.
Description[sr@latin]=Za otkazivanje tuđih izmena u softveru morate se autentifikovati.
Description[sv]=För att avbryta någon annans programvaruändringar måste du utföra behörighetskontroll.
Description[tr]=Diğer bir kişinin yazılım değişikliklerini iptal etmek için kimlik doğrulamanız gerekiyor.
Description[ug]=باشقىلار ئېلىپ يۇمشاق دېتال ئۆزگەرتىشلىرىنى ئەمەلدىن قالدۇرۇش ئۈچۈن دەلىللەش زۆرۈردۇر.
Description[uk]=Для скасування внесення змін до програмного забезпечення, визначеного кимось іншим, вам слід пройти розпізнавання.
Description[x-test]=xxTo cancel someone else's software changes you need to authenticate.xx
Description[zh_CN]=取消其他用户对软件的更改需要您进行认证。
Description[zh_TW]=要取消其他使用者的工作，您必須通過認證。
Policy=auth_admin
Persistence=session
