/***************************************************************************
 *   Copyright © 2012 Jonathan Thomas <echidnaman@kubuntu.org>             *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU General Public License as        *
 *   published by the Free Software Foundation; either version 2 of        *
 *   the License or (at your option) version 3 or any later version        *
 *   accepted by the membership of KDE e.V. (or its successor approved     *
 *   by the membership of KDE e.V.), which shall act as a proxy            *
 *   defined in Section 14 of version 3 of the license.                    *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 ***************************************************************************/

/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i ../downloadprogress.h -c TransactionAdaptor -a transactionadapter.h:transactionadapter.cpp org.kubuntu.qaptworker.transaction.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "transactionadapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TransactionAdaptor
 */

TransactionAdaptor::TransactionAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TransactionAdaptor::~TransactionAdaptor()
{
    // destructor
}

QString TransactionAdaptor::debconfPipe() const
{
    // get the value of property debconfPipe
    return qvariant_cast< QString >(parent()->property("debconfPipe"));
}

// HAND_EDIT: Change type to QApt::DownloadProgress
QApt::DownloadProgress TransactionAdaptor::downloadProgress() const
{
    // get the value of property downloadProgress
    return qvariant_cast< QApt::DownloadProgress >(parent()->property("downloadProgress"));
}

int TransactionAdaptor::error() const
{
    // get the value of property error
    return qvariant_cast< int >(parent()->property("error"));
}

int TransactionAdaptor::exitStatus() const
{
    // get the value of property exitStatus
    return qvariant_cast< int >(parent()->property("exitStatus"));
}

bool TransactionAdaptor::isCancellable() const
{
    // get the value of property isCancellable
    return qvariant_cast< bool >(parent()->property("isCancellable"));
}

bool TransactionAdaptor::isCancelled() const
{
    // get the value of property isCancelled
    return qvariant_cast< bool >(parent()->property("isCancelled"));
}

bool TransactionAdaptor::isPaused() const
{
    // get the value of property isPaused
    return qvariant_cast< bool >(parent()->property("isPaused"));
}

QString TransactionAdaptor::locale() const
{
    // get the value of property locale
    return qvariant_cast< QString >(parent()->property("locale"));
}

QVariantMap TransactionAdaptor::packages() const
{
    // get the value of property packages
    return qvariant_cast< QVariantMap >(parent()->property("packages"));
}

int TransactionAdaptor::progress() const
{
    // get the value of property progress
    return qvariant_cast< int >(parent()->property("progress"));
}

QString TransactionAdaptor::proxy() const
{
    // get the value of property proxy
    return qvariant_cast< QString >(parent()->property("proxy"));
}

int TransactionAdaptor::role() const
{
    // get the value of property role
    return qvariant_cast< int >(parent()->property("role"));
}

int TransactionAdaptor::status() const
{
    // get the value of property status
    return qvariant_cast< int >(parent()->property("status"));
}

QString TransactionAdaptor::statusDetails() const
{
    // get the value of property statusDetails
    return qvariant_cast< QString >(parent()->property("statusDetails"));
}

QString TransactionAdaptor::transactionId() const
{
    // get the value of property transactionId
    return qvariant_cast< QString >(parent()->property("transactionId"));
}

int TransactionAdaptor::userId() const
{
    // get the value of property userId
    return qvariant_cast< int >(parent()->property("userId"));
}

void TransactionAdaptor::cancel()
{
    // handle method call org.kubuntu.qaptworker.transaction.cancel
    QMetaObject::invokeMethod(parent(), "cancel");
}

void TransactionAdaptor::provideMedium(const QString &medium)
{
    // handle method call org.kubuntu.qaptworker.transaction.provideMedium
    QMetaObject::invokeMethod(parent(), "provideMedium", Q_ARG(QString, medium));
}

void TransactionAdaptor::run()
{
    // handle method call org.kubuntu.qaptworker.transaction.run
    QMetaObject::invokeMethod(parent(), "run");
}

void TransactionAdaptor::setProperty(int property, const QDBusVariant &value)
{
    // handle method call org.kubuntu.qaptworker.transaction.setProperty
    QMetaObject::invokeMethod(parent(), "setProperty", Q_ARG(int, property), Q_ARG(QDBusVariant, value));
}

