/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -p workerdbus worker/org.kubuntu.qaptworker.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "workerdbus.h"

/*
 * Implementation of interface class OrgKubuntuQaptworkerInterface
 */

OrgKubuntuQaptworkerInterface::OrgKubuntuQaptworkerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKubuntuQaptworkerInterface::~OrgKubuntuQaptworkerInterface()
{
}

